version: '3'

services:
  app:
    build: .
    image: registry.ql6625.fr/fr_ql6625_testapi:1.0.2
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    #    command:
    #      - npx
    #      - tsc-watch
    #      - --onSuccess
    #      - "node ${INSPECT} ."
    volumes:
      - .:/home/node/app

